### ISSUE TITLE
Request Zulip channel for this project

### ISSUE THREAD

**Issue by flip1995** [rust-marker/design#11]
Since we're now at a point where we want to start with the detailed design / implementation, I think it would be good to have a more dynamic channel than GitHub, where we can talk and ask questions.

I'm pretty sure we can ask about a Zulip channel on the official rust-lang Zulip server.

Would you also be interested in this?

**Comment by DevinR528** [comment]
I'd be interested in joining :+1:

**Comment by jhpratt** [comment]
Fine by me.

**Comment by jhpratt** [comment]
While I don't have permission to create a new stream, it turns out anyone can create a user group. I've added everyone in this GitHub org to the `@project-custom-linter` user group on Zulip.

**Comment by flip1995** [comment]
I [requested a Zulip stream](https://rust-lang.zulipchat.com/#narrow/stream/122653-zulip/topic/Zulip.20stream.20for.20rust-linting.20project/near/251203297)

**Comment by xFrednet** [comment]
I've tried a second time requesting one by reaching out to the community email of rust-lang. Their response was that the rust-lang Zulip is reserved for official Rust teams & working group [1](https://forge.rust-lang.org/platforms/zulip.html#streams).

I hope that Marker at one points gets to a size that requires a chat. Discord might be a good solution at that time, but we'll see. For now, I'll close this issue.
